name: cesard
channels:
  - conda-forge
dependencies:
  - asf_search
  - gdal>=3.5.0
  - geopandas
  - lxml
  - multiformats>=0.3.1
  - numpy
  - pandas
  - pip
  - pyproj
  - pyroSAR>=0.35.0
  - pystac>=1.8.0,<1.11.0
  - python>=3.10
  - python-dateutil
  - requests
  - scipy
  - spatialist>=0.19.0
